version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: |
                 echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
                 docker image build -t somkiat/circle .
                 docker image push somkiat/circle
workflows:
    build-and-test:
      jobs:
        - build-and-test
